bbs/urls.py
from django.conf.urls import url,include
from django.urls import re_path

from bbs import views

urlpatterns = [
    re_path(r'^$', views.index),
    re_path(r'^category/(\d+)/$',views.category,name='category_detail'),
    re_path(r'^detail/(\d+)/$',views.ariticle_detail,name='article_detail'),
    re_path(r'^comment/$',views.comment,name='post_comment'),
    re_path(r'^comment_list/(\d+)/$',views.get_comments,name='get_comments'),
    re_path(r'^new_article/$',views.new_article,name='new-article'),
    re_path(r'^file_upload/$',views.file_upload,name='file-upload'),
    re_path(r'^latest_article_count/$',views.get_latest_article_count,name='get_latest_article_count'),
]

s12bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from bbs.views import acc_login, acc_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',acc_login,name='logins'),
    re_path(r'^accounts/login/$', acc_login, name='login'),
    re_path(r'^accounts/logout/$', acc_logout, name='logout'),
    re_path(r'^bbs/', include(("bbs.urls",'bbs'),namespace='bbs')),
    re_path(r'^chat/', include(("webchat.urls",'webchat'),namespace='webchat')),

]

webchat/urls.py
from django.urls import re_path

from webchat import views
urlpatterns = [
    # url(r'^$/', views.acc_login,name='login' ), 这种写法错误,r'^$/'要改成r'^$'
    re_path(r'^$', views.dashboard,name='chat_dashboard' ),
    re_path(r'^msg_send/$',views.send_msg,name='send_msg' ),
    re_path(r'^new_msgs/$',views.get_new_msgs,name='get_new_msgs' ),
    re_path(r'^file_upload/$',views.file_upload,name='file_uploads' ),
]

templates/base.html
<!DOCTYPE html>
<!-- saved from url=(0049)http://v3.bootcss.com/examples/navbar-static-top/ -->
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/bootstrap/css/navbar-static-top.css" rel="stylesheet">
    <link href="/static/bootstrap/css/custom.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <script src="/static/bootstrap/js/ie-emulation-modes-warning.js"></script>

  </head>

  <body>{% csrf_token %}

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/navbar-static-top/#">草榴社区</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          {% block top-head %}
          <ul class="nav navbar-nav">
            {% for category in category_list %}
              {% if category.id == category_obj.id %}
                <li class="active"><a href="{% url 'bbs:category_detail'  category.id  %}">{{ category.name }}</a></li>
              {% else %}
                <li class=""><a href="{% url 'bbs:category_detail' category.id %}">{{ category.name }}</a></li>
              {% endif %}
            {% endfor %}
            <li class="webchat"><a href="{% url 'webchat:chat_dashboard' %}">WEB聊天室</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}

              <li><a href="#">{{request.user.userprofile.name}}</a></li>

              <li><a href="{% url 'logout' %}">logout</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">登录/注册</a></li>
            {% endif %}
            <li class=""><a href="{% url 'bbs:new-article' %}">发贴</a></li>
          </ul>
        {% endblock %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="page-container">
      {% block page-container %}
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
          <h2>your owner stuff</h2>
        </div>
      {% endblock %}
    </div> <!-- /container -->
    <footer class="footer">
      sssss
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/bootstrap/js/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/bootstrap/js/ie10-viewport-bug-workaround.js"></script>


    {% block bottom-js %}

    {% endblock %}

</body></html>

templates/base2.html
<!DOCTYPE html>
<!-- saved from url=(0046)http://v3.bootcss.com/examples/non-responsive/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Note there is no responsive meta tag here -->

    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>Non-responsive Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/bootstrap/css/non-responsive.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <script src="/static/bootstrap/js/ie-emulation-modes-warning.js"></script>

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/non-responsive/#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://v3.bootcss.com/examples/non-responsive/#">Home</a></li>
            <li><a href="http://v3.bootcss.com/examples/non-responsive/#about">About</a></li>
            <li><a href="http://v3.bootcss.com/examples/non-responsive/#contact">Contact</a></li>
            <li class="dropdown">
              <a href="http://v3.bootcss.com/examples/non-responsive/#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Action</a></li>
                <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Another action</a></li>
                <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Separated link</a></li>
                <li><a href="http://v3.bootcss.com/examples/non-responsive/#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Link</a></li>
            <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Link</a></li>
            <li><a href="http://v3.bootcss.com/examples/non-responsive/#">Link</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        <h1>Non-responsive Bootstrap</h1>
        <p class="lead">Disable the responsiveness of Bootstrap by fixing the width of the container and using the first grid system tier. <a href="http://getbootstrap.com/getting-started/#disable-responsive">Read the documentation</a> for more information.</p>
      </div>

      <h3>What changes</h3>
      <p>Note the lack of the <code>&lt;meta name="viewport" content="width=device-width, initial-scale=1"&gt;</code>, which disables the zooming aspect of sites in mobile devices. In addition, we reset our container's width and are basically good to go.</p>

      <h3>Regarding navbars</h3>
      <p>As a heads up, the navbar component is rather tricky here in that the styles for displaying it are rather specific and detailed. Overrides to ensure desktop styles display are not as performant or sleek as one would like. Just be aware there may be potential gotchas as you build on top of this example when using the navbar.</p>

      <h3>Browsers, scrolling, and fixed elements</h3>
      <p>Non-responsive layouts highlight a key drawback to fixed elements. <strong class="text-danger">Any fixed component, such as a fixed navbar, will not be scrollable when the viewport becomes narrower than the page content.</strong> In other words, given the non-responsive container width of 970px and a viewport of 800px, you'll potentially hide 170px of content.</p>
      <p>There is no way around this as it's default browser behavior. The only solution is a responsive layout or using a non-fixed element.</p>

      <h3>Non-responsive grid system</h3>
      <div class="row">
        <div class="col-xs-4">One third</div>
        <div class="col-xs-4">One third</div>
        <div class="col-xs-4">One third</div>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/bootstrap/js/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>

templates/login.html
{% extends 'base.html' %}

{% block page-container %}
<form action="" method="post">{% csrf_token %}
    Username:<input type="text" name="username">
    Password:<input type="password" name="password">
    <input type="submit" value="Log me in">
</form>
<div>
    {% if login_err %}
        <p style="color: red"> {{login_err}}</p>
    {% endif %}
</div>
{% endblock %}