bbs/urls.py
from django.conf.urls import url,include
from django.urls import re_path

from bbs import views

urlpatterns = [
    re_path(r'^$', views.index),
    re_path(r'^category/(\d+)/$',views.category,name='category_detail'),
    re_path(r'^detail/(\d+)/$',views.ariticle_detail,name='article_detail'),
    re_path(r'^comment/$',views.comment,name='post_comment'),
    re_path(r'^comment_list/(\d+)/$',views.get_comments,name='get_comments'),
    re_path(r'^new_article/$',views.new_article,name='new-article'),
    re_path(r'^file_upload/$',views.file_upload,name='file-upload'),
    re_path(r'^latest_article_count/$',views.get_latest_article_count,name='get_latest_article_count'),
]

s12bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from bbs.views import acc_login, acc_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',acc_login,name='logins'),
    re_path(r'^accounts/login/$', acc_login, name='login'),
    re_path(r'^accounts/logout/$', acc_logout, name='logout'),
    re_path(r'^bbs/', include(("bbs.urls",'bbs'),namespace='bbs')),
    re_path(r'^chat/', include(("webchat.urls",'webchat'),namespace='webchat')),

]

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import  ValidationError #这个就是Django admin后台当出错时,抛出的红色错误提示,要自定义错误时,就得引入此方法
import datetime
# Create your models here.
# 论坛帖子表
class Article(models.Model):
    title = models.CharField(max_length=255,verbose_name=u"标题")
    brief = models.CharField(null=True,blank=True,max_length=255,verbose_name=u"描述")
    category = models.ForeignKey("Category",verbose_name=u"所属板块",on_delete=models.CASCADE) #由于Category类在它的下方,所以要引号引起来,Django内部会自动反射去找
    content = models.TextField(verbose_name=u"文章内容")
    head_img = models.ImageField(verbose_name=u"文章标题图片",upload_to="uploads")
    # 默认你如果不设置upload_to,会在Django项目目录根目录下保存上传文件,此字段只存储 文件路径/文件名
    # 当我们结合前端上传文件时,也不会用upload_to 设置上传文件的保存路径,为啥不用,后面会说
    author = models.ForeignKey("UserProfile",verbose_name=u"作者",on_delete=models.CASCADE)
    pub_date = models.DateField(blank=True,null=True,verbose_name=u"创建时间")
    last_modify = models.DateField(auto_now=True,verbose_name=u"修改时间")
    # 需要注意的是一旦设置auto_now=True ,默认在admin后台就是非编辑状态了,也就是在admin后台此字段为隐藏,除非手动设置可编辑属性
    # auto_now 用于修改,auto_now_add用于创建,在admin后台都是默认不可编辑(隐藏)

    priority = models.IntegerField(default=1000,verbose_name=u"优先级")
    status_choices = (('draft',u"草稿"),
                      ('published',u"已发布"),
                      ('hidden',u"隐藏"),
                    )
    status = models.CharField(max_length=64,choices=status_choices,default="published")
    def __str__(self):
        return self.title
    # django 的model类在保存数据时,会默认调用self.clean()方法的,所以可以在clean方法中定义数据的一些验证
    def clean(self):
        # 如果帖子有发布时间,就说明是发布过的帖子,发布过的帖子就不可以把状态在改成草稿状态了
        if self.status == "draft" and self.pub_date is not None:
            raise  ValidationError(u"如果你选择草稿,就不能选择发布日期!")
        # 如果帖子没有发布时间,并且保存状态是发布状态,那么就把发布日期设置成当天
        if self.status == 'published' and self.pub_date is None:
            self.pub_date = datetime.date.today()
    class Meta:
        verbose_name = u"帖子表"
        verbose_name_plural = u"帖子表"

# 评论表
class Comment(models.Model):
    article = models.ForeignKey("Article",verbose_name=u"所属文章",on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self',related_name="my_clildren",blank=True,null=True,verbose_name=u"父评论",on_delete=models.CASCADE)
    comment_choices = ((1,u'评论'),
                       (2,u"点赞"))
    comment_type = models.IntegerField(choices=comment_choices,default=1,verbose_name=u"评论类型")
    user = models.ForeignKey("UserProfile",verbose_name=u"评论人",on_delete=models.CASCADE)
    comment = models.TextField(blank=True,null=True)
    #这里有一个问题,这里我们设置了允许为空,那就意味着我们在页面上点了评论,却又没有输入内容,这样岂不是很不合理.那么怎么实现只要你点了评论,内容就不能为空.
    # 那么我们会问,为什么允许为空,直接不为空就好了.因为我们这里把评论和点赞放到了一张表中,当为点赞时,当然就不需要评论内容了.所以可以为空.
    # 我们会想在前端进行判断或者在views写代码进行判断,这里告诉你这里我们就可以实现这个限制.使用Django中clean()方法,models类在保存之前它会调用self.clean方法,所以我们可以在这里定义clean方法,进行验证
    date = models.DateTimeField(auto_now_add=True,verbose_name=u"评论时间")

    def clean(self):
        # 如果comment的状态为评论,那么评论内容就不能为空
        if self.comment_type ==1 and len(self.comment)==0:
            raise ValidationError(u"评论内容不能为空")
        # 我想知道这个报错显示在什么位置,我们看到每一个字段有报错,也只是显示在form表单的字段上,这里做了判断错误信息会显示在什么地方?
        # 后面把错误信息显示的位置截图展示
    def __str__(self):
        return "%s,P:%s,%s"%(self.article,self.parent_comment_id,self.comment)

    class Meta:
        verbose_name = u"评论表"
        verbose_name_plural = u"评论表"
# 板块表
class Category(models.Model):
    name = models.CharField(max_length=64,unique=True,verbose_name=u"板块名称") #unique是否唯一
    brief = models.CharField(null=True,blank=True,max_length=255,verbose_name=u"描述")
    set_as_top_menu = models.BooleanField(default=False,verbose_name=u"是否将此板块设置在页面顶部")
    positon_index = models.SmallIntegerField(verbose_name=u"顶部展示的位置")
    admins = models.ManyToManyField("UserProfile",blank=True,verbose_name=u"版主")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = u"板块表"
        verbose_name_plural = u"板块表"

from django.contrib.auth.models import User
# 用户表继承Django里的User
class UserProfile(models.Model):
    user = models.OneToOneField(User,verbose_name=u"关联Django内部的用户",on_delete=models.CASCADE)
    name = models.CharField(max_length=32,verbose_name=u"昵称")
    signature = models.CharField(max_length=255,blank=True,null=True,verbose_name=u"签名")
    # head_img = models.ImageField(height_field='150',width_field='150',blank=True,null=True,verbose_name=u"头像",upload_to="uploads")
    head_img = models.ImageField(blank=True,null=True,verbose_name=u"头像",upload_to="uploads")
    #ImageFied字段说明https://docs.djangoproject.com/en/1.9/ref/models/fields/
    #大概的意思是,ImageField 继承的是FileField,除了FileField的属性被继承了,它还有两个属性 ImageField.height_field和ImageField.width_field,设置后当你存入图片字段时,它会把默认尺寸设置成高height_field宽:width_field
    # 如果想在前端上传图像,需要下载一个Pillow模块,具体使用后面会用到
    friends = models.ManyToManyField('self',related_name='my_friends',blank=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"用户表"
        verbose_name_plural = u"用户表"

# 用户组表,其实这里用不到,因为我们使用Django的 User,
class UserGroup(models.Model):
    pass

bbs/forms.py
#_*_coding:utf-8_*_
__author__ = 'ZhouMing'

from django.forms import Form,ModelForm
from bbs import models

class ArticleModelForm(ModelForm):
    class Meta:
        model = models.Article
        exclude = ('author','pub_date','priority',)

    # 先继承,再重写(想重新定义某些字段的属性,必须先继承,在重写,就这样记着)
    def __init__(self,*args,**kwargs):
        super(ArticleModelForm,self).__init__(*args,**kwargs)
        # self.fields['qq'].widget.attrs["class"] = "form-control"

        # for循环每一个字段,修改字段的class属性
        for field_name in self.base_fields:      #self.base_fields说白了就是把所有字段取出来但是是字典的形势
            field = self.base_fields[field_name]
            #这里可以是上面的例子field.widget.attrs["class"] = "form-control",也可以用update,用update的好处就是可以同时修改多个属性了
            field.widget.attrs.update({'class':"form-control"})

bbs/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,redirect
from bbs import models
from django.contrib.auth.decorators import login_required  # login_required 这是装饰器函数
from django.contrib.auth import authenticate,login,logout
import json
from bbs import comment_hander
from bbs import forms

# Create your views here.

category_list = models.Category.objects.filter(set_as_top_menu =True).order_by('positon_index')

def index(request):
    print(category_list)
    category_obj = models.Category.objects.get(positon_index=1)
    article_list = models.Article.objects.filter(status='published')
    return render(request,"bbs/index.html",{'category_list':category_list,
                                            'category_obj':category_obj,
                                            'article_list':article_list})
    # return HttpResponse("OK")

def category(request,id):
    category_obj = models.Category.objects.get(id=id)
    if category_obj.positon_index == 1: #我们把板块"全部"认定为首页显示,把所有的文章都显示出来,首页就认定当position_index 为1时既是首页.
        article_list = models.Article.objects.filter(status='published')
    else:
        article_list = models.Article.objects.filter(category_id = category_obj.id,status='published')
    return render(request,"bbs/index.html",{'category_list':category_list,
                                            'category_obj':category_obj,
                                            'article_list':article_list})

def acc_logout(request):
    logout(request)
    return HttpResponseRedirect('/bbs/')

def acc_login(request):
    if request.method == 'POST':
        user = authenticate(username = request.POST.get('username'),
                            password = request.POST.get('password'))
        if user is not None:
            login(request,user)
            # return redirect('/bbs/')
            return HttpResponseRedirect(request.GET.get('next') or '/bbs/')
        else:
            login_err = 'Wrong username or password'
            return render(request,'login.html',{'login_err':login_err})
    else:
        return render(request,'login.html')

# 定义文章明细页面的视图函数
def ariticle_detail(request,id):
    ariticle_obj = models.Article.objects.get(id = id)
    comment_tree = comment_hander.build_tree(ariticle_obj.comment_set.select_related())  #在这里将这片文章所有的评论传给build_tree函数,生成一个有层级关系的字典
    return render(request,'bbs/article_detail.html',{'article_obj':ariticle_obj,'category_list':category_list})

def comment(request):
    print(request.POST)
    if request.method == 'POST':
        new_comment_obj = models.Comment(

            article_id = request.POST.get('article_id'),
            parent_comment_id = request.POST.get('parent_commet_id' or None),
            comment_type = request.POST.get("comment_type"),
            user_id = request.user.userprofile.id,
                #这里要主要,我们在bbs系统用户验证用的是Django自带的用户验证模块,经过验证的用户其实是admin的后台账户,我们在前台是userprofile和admin的user做了1对1的外键关联.
                #所以这里是 request.user.userprofile.id而不是request.userprofile.id
            comment = request.POST.get('comment'),
        )
        new_comment_obj.save()
    return HttpResponse('post-comment-success')

def get_comments(request,article_id):
    article_obj = models.Article.objects.get(id=article_id)
    comment_tree = comment_hander.build_tree(article_obj.comment_set.select_related())
    tree_html = comment_hander.render_comment_tree(comment_tree)
    return HttpResponse(tree_html)

@login_required(login_url='/login/')
def new_article(request):
    if request.method=="GET":
        article_form = forms.ArticleModelForm() #实例化form类
        return render(request,'bbs/new_article.html',{'article_form':article_form,})
    elif request.method == 'POST':
        print(request.POST)
        print(request.FILES)
        article_form = forms.ArticleModelForm(request.POST,request.FILES)
        if article_form.is_valid():
            data = article_form.cleaned_data
            data['author_id'] = request.user.userprofile.id
            article_obj = models.Article(**data)
            article_obj.save()
            # article_form.save()
        else:
            return render(request,'bbs/new_article.html',{'article_form':article_form,})
        return HttpResponse('创建成功')

def file_upload(request):
    print(request.FILES)
    file_obj = request.FILES.get('filename')

    with open('uploads/%s'%file_obj.name,'wb+') as destination:

        for chunk in file_obj.chunks():

            destination.write(chunk)

    return render(request,'bbs/new_article.html')

def get_latest_article_count(request):

    latest_article_id = request.GET.get("latest_id")

    new_article_count = models.Article.objects.filter(id__gt=latest_article_id).count()

    # print("new article count:",new_article_count)

    return HttpResponse(json.dumps({'new_article_count':new_article_count}))

templates/bbs/article_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block page-container %}
    <div class="wrap-left">
        <div class="article-title-bg">
            {{article_obj.title}}
        </div>
        <div class="article-title-brief">
            <span>作者:{{article_obj.author.name}}</span>
            <span>{{article_obj.pub_date}}</span>
            <span>{% filter_comment article_obj as comments %}</span>
            <span class="glyphicon glyphicon-comment">{{comments.comment_count}}</span>
            <span class="glyphicon glyphicon-thumbs-up">{{comments.thumb_count}}</span>
        </div>
        <div class="article-content">
            <img class="article-detail-img" src="/static/{{article_obj.head_img|truncate_url}}" >
            {{ article_obj.content|safe}}
            <span class="glyphicon glyphicon-comment add-comment "></span>
        </div>

        <div class="comment-box">
            {% if request.user.is_authenticated %}
                <div class="new-comment-box">
                    <textarea class="form-control" rows="3"></textarea>
                    <button type="button" style="margin-top: 5px;margin-bottom: 5px;" class="btn btn-success pull-right">评论</button>
                </div>
            {% else %}
                <div class="new-comment-box">
                    <div class="jumbotron">
                      <p style="text-align:center;"><a href="{% url 'login' %}?next={{ request.path }}" style="color: blue">登录</a>后参与评论</p>
                    </div>
                </div>
            {% endif %}
            <button type="button" onclick="GetComments()">测试获取评论</button>
            <div class="comment-list" style="margin-left: 10px">

            </div>
        </div>


    </div>
    <div class="wrap-right">
        sss
    </div>
    <div class="clear-both"></div>

{% endblock %}




{% block bottom-js %}
<script>
    function GetComments(){
        $.get("{% url 'bbs:get_comments' article_obj.id %}",function(callback){
            //console.log(callback);
            $(".comment-list").html(callback);
            /*
            // start add comment 绑定click事件
            $(".add-comment").click(function(){
                var comment_id = $(this).parent().attr('comment-id');
                console.log(comment_id)
            });
            // end add comment
            */
        });
    }
    function getCsrf(){
        return $("input[name='csrfmiddlewaretoken']").val();
    }
    $(document).ready(function(){
        GetComments();
        $(".wrap-left").delegate(" .add-comment ",'click',function(){
            var comment_id = $(this).parent().attr('comment-id');
            $('.new-comment-box textarea').val(''); //在克隆之前把评论输入框的内容清空.
            var new_comment_box_div = $('.new-comment-box').clone(true);
            $('.new-comment-box').remove();
            $(this).parent().append(new_comment_box_div);
        });

        $(".new-comment-box .btn").click(function(){
            var comment_text = $(".new-comment-box textarea").val();
            if (comment_text.trim().length < 5){
                alert("评论不能少于5个字sb")
            }else{
                //post
                if ($(this).parent().parent().attr('comment-id')){
//                if ($('.new-comment-box').parent().attr('comment-id')){
                    var parent_comment_id =  $('.new-comment-box').parent().attr('comment-id');
                } else{
                    var parent_comment_id = null;
                }

                $.post("{% url 'bbs:post_comment' %}",
                        {
                            'comment_type':1,
                            'article_id':"{{ article_obj.id }}",
                            parent_commet_id:parent_comment_id,
                            'comment':comment_text.trim(),
                            'csrfmiddlewaretoken':getCsrf()
                        },//end post args
                        function(callback){
                            //console.log(callback)
                            if (callback == 'post-comment-success'){
                                alert('successful');
                                $('.new-comment-box textarea').val('');
                                $('.new-comment-box').prependTo($('.comment-box'));
                                GetComments();//新评论提交后,重新加载评论内容到页面.
                            }
                });//end post
            }
        });//end button click

    });

</script>

{% endblock %}

templates/bbs/index.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block page-container %}
    <div class="wrap-left">
        <div class="new_article_notify hide">
            你有<span></span>新消息
        </div>
        {% for article in article_list reversed %}
            <div article_id="{{article.id}}" class="article-box row">
                <div class="atricle-head-img col-md-5">
                    <img src="/static/{{ article.head_img | truncate_url }}"/>
                </div>
                <div class="col-md-7">
                    <div class="article-title">
                        <a href="{% url 'bbs:article_detail' article.id %} ">{{article.title}}</a>
                    </div>
                    <div class="article-brief">
                        {{article.brief}}
                    </div>
                    <div class="article-brief-info">
                        <span>{{article.author.name}}</span>
                        <span>{{article.pub_date}}</span>
                        <span>{% filter_comment article as comments %}</span>
                        <span class="glyphicon glyphicon-comment">{{comments.comment_count}}</span>
                        <span class="glyphicon glyphicon-thumbs-up">{{comments.thumb_count}}</span>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
    <div class="wrap-right">
        sss
    </div>
    <div class="clear-both"></div>

{% endblock %}

{% block bottom-js %}
<!--//首先要等文档数加载完成后在执行定时任务-->
<script>
    $(document).ready(function(){
       var new_article_refresh = setInterval(function(){
//           var latest_article_id = $(".wrap-left").children(':first').attr("article_id");
           var latest_article_id = $($(".wrap-left").children()[1]).attr("article_id");
           $.getJSON("{% url 'bbs:get_latest_article_count' %}",
                   {"latest_id":latest_article_id},
                   function(callback){
//                       console.log(callback);
                       if(callback.new_article_count >0){
                           console.log('1111')
                           if($(".new_article_notify").hasClass("hide")){
                               $(".new_article_notify").removeClass("hide")
                               console.log('22222')
                           }
                           $(".new_article_notify span").html(callback.new_article_count)
                       }
                   }
           );
           console.log(latest_article_id);
       },3000);
    });
</script>
{% endblock %}

templates/bbs/new_article.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block page-container %}
    <div class="wrap-left">
        <form method="post" enctype="multipart/form-data" > {% csrf_token %}
            {{ article_form }}
            <!--<textarea name="article-content"></textarea>-->
            <input type="submit" class="btn btn-success pull-right" style="" value="发帖"/>
        </form>
        <form method="post" enctype="multipart/form-data" action="{% url 'bbs:file-upload' %}"> {% csrf_token %}
            <input name='filename' type="file">
            <input type="submit" value="上传文件">
        </form>
    </div>
    <div class="wrap-right">
        sss
    </div>
    <div class="clear-both"></div>
{% endblock %}

{% block bottom-js %}
<script src="/static/plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('id_content')
</script>
{% endblock %}