bbs/urls.py
from django.conf.urls import url,include
from django.urls import re_path

from bbs import views

urlpatterns = [
    re_path(r'^$', views.index),
    re_path(r'^category/(\d+)/$',views.category,name='category_detail'),
    re_path(r'^detail/(\d+)/$',views.ariticle_detail,name='article_detail'),
    re_path(r'^comment/$',views.comment,name='post_comment'),
    re_path(r'^comment_list/(\d+)/$',views.get_comments,name='get_comments'),
    re_path(r'^new_article/$',views.new_article,name='new-article'),
    re_path(r'^file_upload/$',views.file_upload,name='file-upload'),
    re_path(r'^latest_article_count/$',views.get_latest_article_count,name='get_latest_article_count'),
]

s12bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from bbs.views import acc_login, acc_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',acc_login,name='logins'),
    re_path(r'^accounts/login/$', acc_login, name='login'),
    re_path(r'^accounts/logout/$', acc_logout, name='logout'),
    re_path(r'^bbs/', include(("bbs.urls",'bbs'),namespace='bbs')),
    re_path(r'^chat/', include(("webchat.urls",'webchat'),namespace='webchat')),

]

webchat/urls.py
from django.urls import re_path

from webchat import views
urlpatterns = [
    # url(r'^$/', views.acc_login,name='login' ), 这种写法错误,r'^$/'要改成r'^$'
    re_path(r'^$', views.dashboard,name='chat_dashboard' ),
    re_path(r'^msg_send/$',views.send_msg,name='send_msg' ),
    re_path(r'^new_msgs/$',views.get_new_msgs,name='get_new_msgs' ),
    re_path(r'^file_upload/$',views.file_upload,name='file_uploads' ),
]

webchat/models.py
from django.db import models
from bbs.models import UserProfile
# Create your models here.
class  WebGroup(models.Model):
    name = models.CharField(max_length=64)
    brief = models.CharField(max_length=255,blank=True,null=True)
    owner = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    admins = models.ManyToManyField(UserProfile,blank=True,related_name='group_admins')
    members = models.ManyToManyField(UserProfile,blank=True,related_name='group_members')
    max_members = models.IntegerField(default=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u"聊天组"
        verbose_name_plural = u"聊天组"

webchat/views.py
from django.shortcuts import render,HttpResponse
from django.contrib.auth.decorators import  login_required
import json,queue,time
from webchat import models
# Create your views here.

GLOBAL_MSG_QUEUES={

}
@login_required
def dashboard(request):
    # return HttpResponse('ok')
    return render(request,'webchat/dashboard.html')

@login_required
def send_msg(request):
    print(request.POST)
    msg_data = request.POST.get('data')
    if msg_data:
        msg_data = json.loads(msg_data)
        msg_data['timestamp'] = time.time()
        if msg_data['type'] == 'single':
            if not GLOBAL_MSG_QUEUES.get(int(msg_data['to'])):
                GLOBAL_MSG_QUEUES[int(msg_data['to'])] = queue.Queue()
            GLOBAL_MSG_QUEUES[int(msg_data['to'])].put(msg_data)
        else: #group
            #找到这个组里的所有成员,把发给该组的消息发给所有成员
            group_obj = models.WebGroup.objects.get(id = int(msg_data['to']))

            for member in group_obj.members.select_related():
                if not GLOBAL_MSG_QUEUES.get(member.id):
                    GLOBAL_MSG_QUEUES[member.id] = queue.Queue()
                if member.id != request.user.userprofile.id:
                    GLOBAL_MSG_QUEUES[member.id].put(msg_data)

    print(GLOBAL_MSG_QUEUES)
    return HttpResponse("---msg recevied---")

def get_new_msgs(request):
    # 先判断自己有没有queue,如果是新用户第一次登录就是没有queue
    if request.user.userprofile.id not in GLOBAL_MSG_QUEUES:
        print("no queue for user[%s]"%request.user.userprofile.id,request.user)
        GLOBAL_MSG_QUEUES[request.user.userprofile.id] = queue.Queue() #创建一个queue
    msg_count = GLOBAL_MSG_QUEUES[request.user.userprofile.id].qsize() #获取queue的大小
    q_obj = GLOBAL_MSG_QUEUES[request.user.userprofile.id]
    msg_list = []
    if msg_count > 0:
        for msg in range(msg_count):
            msg_list.append(q_obj.get()) #q_obj.get()不需要指定参数,会找最旧的那一条
        print("new msgs:",msg_list)
    else:#没消息,要挂起
        print(GLOBAL_MSG_QUEUES)
        try:
            msg_list.append(q_obj.get(timeout=60)) #如果有消息,则立刻加入到msg_list列表,如果超时进入except
        except queue.Empty:     #如果列表为空,打印下面消息
            print("\033[41;1mno msg for [%s][%s]\033[0m"%(request.user.userprofile.id,request.user))
    return HttpResponse(json.dumps(msg_list))


def file_upload(request):
    print(request.POST,request.FILES)
    file_obj = request.FILES.get('file')
    new_file_name = "uploads/%s"%file_obj.name
    with open(new_file_name,"wb+") as new_file_obj:
        for chunk in file_obj.chunks():
            new_file_obj.write(chunk)
    return HttpResponse('--upload success---')

templates/webchat/dashboard.html
{% extends 'base.html' %}

{% block page-container%}
<div class="chat-container">
    <div class="left-contact-panel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#contact-tab" role="tab" data-toggle="tab">好友列表</a></li>
          <li role="presentation"><a href="#group-tab" role="tab" data-toggle="tab">分组列表</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="contact-tab">
              <ul class="list-group">
                {% for friend in request.user.userprofile.friends.select_related %}
                  <li contact-type='single' contact-id='{{friend.id}}' onclick="OpenChatWindow(this)" class="list-group-item">
                      <span class="badge hide">0</span>
                      <span class="contact-name">{{friend.name}}</span>
                  </li>
                {% endfor%}
              </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="group-tab">
            <ul class="list-group">
                {% for group in request.user.userprofile.group_members.select_related%}
                    <li contact-type='group' contact-id="{{group.id}}" onclick="OpenChatWindow(this)" class="list-group-item">
                        <span class="badge hide">0</span>
                        <span class="contact-name">{{ group.name }}</span>
                    </li>

                {% endfor%}
            </ul>
          </div>
        </div>
    </div>
    <div class="right-chat-panel">
        <div class="chat-box-title" contact-id = "" contact-type="">
            title
        </div>
        <div class="chat-box-window">
            window
        </div>
        <div class="chat-box-emoj">
            <!--emoj-->
            <div class="col-md-3">
                <input id="file_upload" name="filename" type="file">
            </div>
            <div class="col-md-2">
               <span class="glyphicon glyphicon-upload" onclick="UploadFiles()"></span>
            </div>

        </div>
        <div class="chat-box-msg-box">
            <textarea name="" id="msg" ></textarea>
            <button class="btn btn-success">发送消息</button>
        </div>

    </div>
    <div class="clear-both"></div>
</div>
{% endblock %}

{% block bottom-js %}
<script>
    // for csrf
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    //end csrf
//global chat record
GLOBAL_CHAT_RECORD_DIC = {
    'single':{},
    'group':{},
};
    $(document).ready(function(){
        //set csrf befor send ajax
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        // end set csrf

        GetNewMsgs();

        // 让webchat页面的标高亮
        $("#navbar a[href='{{ request.path }}']").parent().addClass('active');
        // end 让webchat页面的标高亮

        //send msg
        $("body").delegate("textarea","keydown",function(e){
            //send msg button clicked
            if (e.which == 13 ){
                var msg_text=$("textarea").val();
                if ($.trim(msg_text).length >0){
//                    console.log(msg_text);
                    SendMsg(msg_text);
                }
                //no wait the send_msg's call confirm msg

                AddSentMsgIntoBox(msg_text);

                $("textarea").val('');
            }

        });
    });

    function SendMsg(msg_text){
        var contact_type = $(".chat-box-title").attr("contact-type");
        var contact_id = $(".chat-box-title").attr("contact-id");
        //start if
        if (contact_type && contact_id){
            var msg_item={
                'from':"{{ request.user.userprofile.id }}",
                'from_name':"{{ request.user.userprofile.name }}",
                'to': contact_id,
                'type':contact_type,
                'msg':msg_text
            };
//            $.post("{% url 'webchat:send_msg' %}",msg_item,function(callback){
            $.post("{% url 'webchat:send_msg' %}",{data:JSON.stringify(msg_item)},function(callback){
                console.log(callback)
            });//end post
        }
        //end if
    }

    function AddSentMsgIntoBox(msg_tex){
        var new_msg_ele = "<div class='msg-item'>" +
                            "<span>"+ "{{ request.user.userprofile.name }}"+"</span>" +
                            "<span>"+ new Date().toLocaleTimeString()+"</span>" +
                            "<div class='msg-text'>" + msg_tex + "</div>" +
                          "</div>";
        $(".chat-box-window").append(new_msg_ele);

        // 动画效果滑动
//        console.log($('.chat-box-window')[0]);
//        $(".chat-box-window").animate({scrollTop:$('.chat-box-window')[0].scrollHeight},500)


//        console.log($('.chat-box-window'));
//        console.log($('.chat-box-window')[0]);
        $(".chat-box-window").animate({scrollTop:$('.chat-box-window').height()},500)
    }

    function OpenChatWindow(ele){
//        console.log($(ele));

        //在切换之前把当前的聊天纪录归档
        var current_session_id = $(".chat-box-title").attr("contact-id");
        var current_session_type = $(".chat-box-title").attr("contact-type");
        //由于chat-box-title所在的div 默认是没有contact-id和contact-type两个属性的.所以我们要判断只有当有的时候才有必要消息存储到全局字典中
        if (current_session_id){ //has session_id
            //把旧的内容dump进字典
            GLOBAL_CHAT_RECORD_DIC[current_session_type][current_session_id] = $(".chat-box-window").html();

        }

        $(ele).addClass("active");
        $(ele).siblings().removeClass("active");
        //把消息提醒数改成0 ,并且class加上hide
        $(ele).find(".badge").text(0)
        $(ele).find(".badge").addClass("hide")


        var contact_id = $(ele).attr("contact-id");
        var contact_name = $(ele).find(".contact-name").text();
        var contact_type = $(ele).attr("contact-type");

//        然后把右边的title内容改掉
        var chat_box_title_content = "正在跟 " + contact_name + " 聊天";
        $(".chat-box-title").attr("contact-type",contact_type);
        $(".chat-box-title").attr("contact-id",contact_id);
        $(".chat-box-title").html(chat_box_title_content);

        //将新内容loads到页面中
        var new_contact_chat_record  = ""
        if ( GLOBAL_CHAT_RECORD_DIC[contact_type][contact_id]){ //判断字典中有没有存储,有说明之前dump过,没有说明是之前没聊过
             var new_contact_chat_record = GLOBAL_CHAT_RECORD_DIC[contact_type][contact_id]
        }
        $(".chat-box-window").html(new_contact_chat_record)
    }




    function GetNewMsgs(){
        $.getJSON("{% url 'webchat:get_new_msgs' %}",function(callback){
            console.log(callback);
            console.log(123123123);
            ParseNewMsgs(callback); //把新消息进行解析
            GetNewMsgs();
        });
    }

    function ParseNewMsgs(callback){
        //先获取正在打开的消息窗口是和谁聊天的
        var current_session_type = $(".chat-box-title").attr("contact-type");
        var current_session_id = $(".chat-box-title").attr("contact-id");
        for( var i in callback){
            console.log(callback[i]); //循环出来的是一个索引
            //前端打印结果是 Object {msg: "↵45", from: "1", to: "2", type: "single", timestamp: 1476167618.588683}
            // 现在我们要把这个object拼接成前端的html代码.
            var new_msg_ele = "<div class='msg-item'>" +
                        "<span>"+ callback[i].from_name +"</span>" +
                        "<span>"+ callback[i].timestamp+"</span>" +
                        "<div class='msg-text'>" + callback[i].msg + "</div>" +
                      "</div>";

            if (callback[i].type == "single"){
                var msg_from_contact_id = callback[i]['from'];
            } else {
                var msg_from_contact_id = callback[i]['to']
            }

            if (msg_from_contact_id == current_session_id && callback[i].type == current_session_type){
                //代表此消息的发送方是当前打开的消息窗口所属的对象
                $(".chat-box-window").append(new_msg_ele)
            } else {
                //此消息的发送方 不是当前打开的消息窗口所属的对象
                if ( GLOBAL_CHAT_RECORD_DIC[callback[i].type][msg_from_contact_id]){ //判断字典中有没有存储,有说明之前dump过,没有说明是之前没聊过
                     GLOBAL_CHAT_RECORD_DIC[callback[i].type][msg_from_contact_id] += new_msg_ele
                } else {
                    GLOBAL_CHAT_RECORD_DIC[callback[i].type][msg_from_contact_id] = new_msg_ele
                }//end if

                // 新消息提醒
                var contact_ele = $(".list-group li[contact-type='"+ callback[i].type +"']").filter("li[contact-id="+ msg_from_contact_id +"]")[0]
                var current_new_msg_num = $(contact_ele).find(".badge").text();
                $(contact_ele).find(".badge").removeClass("hide");
                $(contact_ele).find(".badge").text(parseInt(current_new_msg_num)+1);

            }

        }
    }
    function UploadFiles(){
        var formData = new FormData();
        console.log($('#file_upload')[0].files[0]);
        formData.append('file',$('#file_upload')[0].files[0]);

        $.ajax({
            url: "{% url 'webchat:file_uploads' %}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function(data){
                console.log(data);
                //alert(data);
            }
        });
    }

</script>
{% endblock%}